---
- hosts: all
  become: true
  roles:
    - common
  tags:
    - common

- hosts: test
  become: true
  roles:
    - os-hardening
  tags:
    - base

- name: Install Zookeeper
  hosts: zookeeper
  become: true
  vars:
    zookeeper_id: "{{  ansible_default_ipv4.address | splitext | last | replace('.', '') }}"
    zookeeper_servers: "{{ groups['zookeeper'] }}"
  roles:
    - role: geerlingguy.java
      java_packages:
        - java-11-openjdk-headless.x86_64
    - sleighzy.zookeeper
    - zk-tweaks
  tags:
    - zookeeper

- name: Install NiFi
  hosts: nifi
  become: true
  vars: 
      nifi_log_level_root: WARN
      nifi_node_jvm_memory: '2048M'
      nifi_single_node: False
      nifi_zookeeper_servers:
        - zk-1.dev.shearn89.com
        - zk-2.dev.shearn89.com
        - zk-3.dev.shearn89.com
      nifi_state_management_embedded_zookeeper_start: False
      nifi_version: 1.12.1
      nifi_is_secure: True
      nifi_initial_admin: SHEARNA@DEV.SHEARN89.COM
      nifi_security_keystore: /etc/pki/java/keystore.jks
      nifi_security_keystoreType: JKS
      nifi_security_keystorePasswd: changeit
      nifi_security_truststore: /etc/pki/java/cacerts
      nifi_security_truststoreType: JKS
      nifi_security_truststorePasswd: changeit
      nifi_enable_anonymous_auth: true
      nifi_log_app_file_retention: 10
      nifi_log_user_file_retention: 10
      nifi_perform_restart: False
  pre_tasks:
  roles:
    - role: nifi-prereqs
      nifi_version: 1.12.1
    - role: nifi
      nifi_version: 1.12.1
  tags:
    - nifi
