---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: test
  roles:
    - os-hardening
  tags:
    - base

- name: Install NiFi
  hosts: nifi
  vars: 
      nifi_log_level_root: WARN
      nifi_node_jvm_memory: '2048M'
      nifi_single_node: False
      nifi_authorized_nodes_list:
        - CN=nifi-1.dev.shearn89.com, O=DEV.SHEARN89.COM
        - CN=nifi-2.dev.shearn89.com, O=DEV.SHEARN89.COM
        - CN=nifi-3.dev.shearn89.com, O=DEV.SHEARN89.COM
      nifi_zookeeper_servers:
        - 192.168.89.51
        - 192.168.89.52
        - 192.168.89.53
      nifi_state_management_embedded_zookeeper_start: True
      nifi_version: 1.12.1
      nifi_is_secure: True
      nifi_initial_admin: SHEARNA@DEV.SHEARN89.COM
      nifi_security_keystore: /etc/pki/java/keystore.jks
      nifi_security_keystoreType: JKS
      nifi_security_keystorePasswd: changeit
      nifi_security_truststore: /etc/pki/java/cacerts
      nifi_security_truststoreType: JKS
      nifi_security_truststorePasswd: changeit
      nifi_enable_anonymous_auth: true
  pre_tasks:
  roles:
    - role: nifi-prereqs
      nifi_version: 1.12.1
    - role: nifi
      nifi_version: 1.12.1
  tags:
    - nifi
