---
- name: install foreman repos
  debug:
    msg: "todo"

- name: install epel repo
  package:
    name: epel-release
    state: present

- name: install extra packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - httpie
    - wget
    - vim
    - git
    - ipa-client
    - kernel-devel
    - kernel-headers
    - openssl-devel
    - make
    - glibc-devel
    - dkms
    - mlocate

- name: get cert from IPA
  command: "ipa-getcert request -k /etc/pki/tls/private/{{ inventory_hostname_short }}.pem -f /etc/pki/tls/certs/{{ inventory_hostname_short }}.pem"
  args:
    creates: "/etc/pki/tls/certs/{{ inventory_hostname_short }}.pem"

- name: install katello certs for openscap scan results
  package:
    name: https://satellite.dev.shearn89.com/pub/katello-ca-consumer-latest.noarch.rpm
    state: present

- name: install check-mk-agent
  package:
    name: https://monitor.dev.shearn89.com/cmk/check_mk/agents/check-mk-agent-2.0.0-1.noarch.rpm
    state: present

- name: open firewall for cmk agent
  firewalld:
    port: 6556/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: copy add-to-cmk.sh
  copy:
    src: add-to-cmk.sh
    dest: /root/add-to-cmk.sh
    owner: root
    group: root
    mode: 0750

- name: run add-to-cmk.sh
  command:
    cmd: /root/add-to-cmk.sh
    creates: /opt/.cmk_added

- name: fix postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces = '
    line: 'inet_interfaces = localhost'
  notify: restart-postfix

- name: fix postfix 2
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_protocols = '
    line: 'inet_protocols = ipv4'
  notify: restart-postfix

- name: fix authconfig
  command: authconfig --enablesssd --enablesssdauth --updateall
